//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Rollup
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const rollupABI = [
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'previousAdmin', internalType: 'address', type: 'address', indexed: false },
      { name: 'newAdmin', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'AdminChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'beacon', internalType: 'address', type: 'address', indexed: true }],
    name: 'BeaconUpgraded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'nodeNum', internalType: 'uint64', type: 'uint64', indexed: true },
      { name: 'blockHash', internalType: 'bytes32', type: 'bytes32', indexed: false },
      { name: 'sendRoot', internalType: 'bytes32', type: 'bytes32', indexed: false },
    ],
    name: 'NodeConfirmed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'nodeNum', internalType: 'uint64', type: 'uint64', indexed: true },
      { name: 'parentNodeHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'nodeHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'executionHash', internalType: 'bytes32', type: 'bytes32', indexed: false },
      {
        name: 'assertion',
        internalType: 'struct Assertion',
        type: 'tuple',
        components: [
          {
            name: 'beforeState',
            internalType: 'struct ExecutionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct ExecutionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
            ],
          },
          { name: 'numBlocks', internalType: 'uint64', type: 'uint64' },
        ],
        indexed: false,
      },
      { name: 'afterInboxBatchAcc', internalType: 'bytes32', type: 'bytes32', indexed: false },
      { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32', indexed: false },
      { name: 'inboxMaxCount', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'NodeCreated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'nodeNum', internalType: 'uint64', type: 'uint64', indexed: true }],
    name: 'NodeRejected',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256', indexed: true }],
    name: 'OwnerFunctionCalled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'account', internalType: 'address', type: 'address', indexed: false }],
    name: 'Paused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'challengeIndex', internalType: 'uint64', type: 'uint64', indexed: true },
      { name: 'asserter', internalType: 'address', type: 'address', indexed: false },
      { name: 'challenger', internalType: 'address', type: 'address', indexed: false },
      { name: 'challengedNode', internalType: 'uint64', type: 'uint64', indexed: false },
    ],
    name: 'RollupChallengeStarted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'machineHash', internalType: 'bytes32', type: 'bytes32', indexed: false },
      { name: 'chainId', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'RollupInitialized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'account', internalType: 'address', type: 'address', indexed: false }],
    name: 'Unpaused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'implementation', internalType: 'address', type: 'address', indexed: true }],
    name: 'Upgraded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'implementation', internalType: 'address', type: 'address', indexed: true }],
    name: 'UpgradedSecondary',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'initialBalance', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'finalBalance', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'UserStakeUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'initialBalance', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'finalBalance', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'UserWithdrawableFundsUpdated',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: '_stakerMap',
    outputs: [
      { name: 'amountStaked', internalType: 'uint256', type: 'uint256' },
      { name: 'index', internalType: 'uint64', type: 'uint64' },
      { name: 'latestStakedNode', internalType: 'uint64', type: 'uint64' },
      { name: 'currentChallenge', internalType: 'uint64', type: 'uint64' },
      { name: 'isStaked', internalType: 'bool', type: 'bool' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'amountStaked',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'baseStake',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'bridge',
    outputs: [{ name: '', internalType: 'contract IBridge', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'chainId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'challengeManager',
    outputs: [{ name: '', internalType: 'contract IChallengeManager', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'confirmPeriodBlocks',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: 'assertion',
        internalType: 'struct Assertion',
        type: 'tuple',
        components: [
          {
            name: 'beforeState',
            internalType: 'struct ExecutionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct ExecutionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
            ],
          },
          { name: 'numBlocks', internalType: 'uint64', type: 'uint64' },
        ],
      },
    ],
    name: 'createNitroMigrationGenesis',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'currentChallenge',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'extraChallengeTimeBlocks',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'firstUnresolvedNode',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'nodeNum', internalType: 'uint64', type: 'uint64' },
      { name: 'blockHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'sendRoot', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'forceConfirmNode',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'prevNode', internalType: 'uint64', type: 'uint64' },
      { name: 'prevNodeInboxMaxCount', internalType: 'uint256', type: 'uint256' },
      {
        name: 'assertion',
        internalType: 'struct Assertion',
        type: 'tuple',
        components: [
          {
            name: 'beforeState',
            internalType: 'struct ExecutionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct ExecutionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
            ],
          },
          { name: 'numBlocks', internalType: 'uint64', type: 'uint64' },
        ],
      },
      { name: 'expectedNodeHash', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'forceCreateNode',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address[]', type: 'address[]' }],
    name: 'forceRefundStaker',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'stakerA', internalType: 'address[]', type: 'address[]' },
      { name: 'stakerB', internalType: 'address[]', type: 'address[]' },
    ],
    name: 'forceResolveChallenge',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'nodeNum', internalType: 'uint64', type: 'uint64' }],
    name: 'getNode',
    outputs: [
      {
        name: '',
        internalType: 'struct Node',
        type: 'tuple',
        components: [
          { name: 'stateHash', internalType: 'bytes32', type: 'bytes32' },
          { name: 'challengeHash', internalType: 'bytes32', type: 'bytes32' },
          { name: 'confirmData', internalType: 'bytes32', type: 'bytes32' },
          { name: 'prevNum', internalType: 'uint64', type: 'uint64' },
          { name: 'deadlineBlock', internalType: 'uint64', type: 'uint64' },
          { name: 'noChildConfirmedBeforeBlock', internalType: 'uint64', type: 'uint64' },
          { name: 'stakerCount', internalType: 'uint64', type: 'uint64' },
          { name: 'childStakerCount', internalType: 'uint64', type: 'uint64' },
          { name: 'firstChildBlock', internalType: 'uint64', type: 'uint64' },
          { name: 'latestChildNumber', internalType: 'uint64', type: 'uint64' },
          { name: 'createdAtBlock', internalType: 'uint64', type: 'uint64' },
          { name: 'nodeHash', internalType: 'bytes32', type: 'bytes32' },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'nodeNum', internalType: 'uint64', type: 'uint64' }],
    name: 'getNodeCreationBlockForLogLookup',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'getStaker',
    outputs: [
      {
        name: '',
        internalType: 'struct IRollupCore.Staker',
        type: 'tuple',
        components: [
          { name: 'amountStaked', internalType: 'uint256', type: 'uint256' },
          { name: 'index', internalType: 'uint64', type: 'uint64' },
          { name: 'latestStakedNode', internalType: 'uint64', type: 'uint64' },
          { name: 'currentChallenge', internalType: 'uint64', type: 'uint64' },
          { name: 'isStaked', internalType: 'bool', type: 'bool' },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'stakerNum', internalType: 'uint64', type: 'uint64' }],
    name: 'getStakerAddress',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'inbox',
    outputs: [{ name: '', internalType: 'contract IInboxBase', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: 'config',
        internalType: 'struct Config',
        type: 'tuple',
        components: [
          { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64' },
          { name: 'extraChallengeTimeBlocks', internalType: 'uint64', type: 'uint64' },
          { name: 'stakeToken', internalType: 'address', type: 'address' },
          { name: 'baseStake', internalType: 'uint256', type: 'uint256' },
          { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32' },
          { name: 'owner', internalType: 'address', type: 'address' },
          { name: 'loserStakeEscrow', internalType: 'address', type: 'address' },
          { name: 'chainId', internalType: 'uint256', type: 'uint256' },
          { name: 'chainConfig', internalType: 'string', type: 'string' },
          { name: 'genesisBlockNum', internalType: 'uint64', type: 'uint64' },
          {
            name: 'sequencerInboxMaxTimeVariation',
            internalType: 'struct ISequencerInbox.MaxTimeVariation',
            type: 'tuple',
            components: [
              { name: 'delayBlocks', internalType: 'uint256', type: 'uint256' },
              { name: 'futureBlocks', internalType: 'uint256', type: 'uint256' },
              { name: 'delaySeconds', internalType: 'uint256', type: 'uint256' },
              { name: 'futureSeconds', internalType: 'uint256', type: 'uint256' },
            ],
          },
        ],
      },
      {
        name: 'connectedContracts',
        internalType: 'struct ContractDependencies',
        type: 'tuple',
        components: [
          { name: 'bridge', internalType: 'contract IBridge', type: 'address' },
          { name: 'sequencerInbox', internalType: 'contract ISequencerInbox', type: 'address' },
          { name: 'inbox', internalType: 'contract IInboxBase', type: 'address' },
          { name: 'outbox', internalType: 'contract IOutbox', type: 'address' },
          { name: 'rollupEventInbox', internalType: 'contract IRollupEventInbox', type: 'address' },
          { name: 'challengeManager', internalType: 'contract IChallengeManager', type: 'address' },
          { name: 'rollupAdminLogic', internalType: 'address', type: 'address' },
          { name: 'rollupUserLogic', internalType: 'contract IRollupUser', type: 'address' },
          { name: 'validatorUtils', internalType: 'address', type: 'address' },
          { name: 'validatorWalletCreator', internalType: 'address', type: 'address' },
        ],
      },
    ],
    name: 'initialize',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'isStaked',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'isStakedOnLatestConfirmed',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'isValidator',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'isZombie',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'lastStakeBlock',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'latestConfirmed',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'latestNodeCreated',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'latestStakedNode',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'loserStakeEscrow',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'minimumAssertionPeriod',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'nodeNum', internalType: 'uint64', type: 'uint64' },
      { name: 'staker', internalType: 'address', type: 'address' },
    ],
    name: 'nodeHasStaker',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'outbox',
    outputs: [{ name: '', internalType: 'contract IOutbox', type: 'address' }],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'pause', outputs: [] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'paused',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_outbox', internalType: 'address', type: 'address' }],
    name: 'removeOldOutbox',
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'resume', outputs: [] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'rollupDeploymentBlock',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'rollupEventInbox',
    outputs: [{ name: '', internalType: 'contract IRollupEventInbox', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'sequencerInbox',
    outputs: [{ name: '', internalType: 'contract ISequencerInbox', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newBaseStake', internalType: 'uint256', type: 'uint256' }],
    name: 'setBaseStake',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newConfirmPeriod', internalType: 'uint64', type: 'uint64' }],
    name: 'setConfirmPeriodBlocks',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_inbox', internalType: 'address', type: 'address' },
      { name: '_enabled', internalType: 'bool', type: 'bool' },
    ],
    name: 'setDelayedInbox',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newExtraTimeBlocks', internalType: 'uint64', type: 'uint64' }],
    name: 'setExtraChallengeTimeBlocks',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newInbox', internalType: 'contract IInboxBase', type: 'address' }],
    name: 'setInbox',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newLoserStakerEscrow', internalType: 'address', type: 'address' }],
    name: 'setLoserStakeEscrow',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newPeriod', internalType: 'uint256', type: 'uint256' }],
    name: 'setMinimumAssertionPeriod',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_outbox', internalType: 'contract IOutbox', type: 'address' }],
    name: 'setOutbox',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'setOwner',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_sequencerInbox', internalType: 'address', type: 'address' }],
    name: 'setSequencerInbox',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newStakeToken', internalType: 'address', type: 'address' }],
    name: 'setStakeToken',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_validator', internalType: 'address[]', type: 'address[]' },
      { name: '_val', internalType: 'bool[]', type: 'bool[]' },
    ],
    name: 'setValidator',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_validatorWhitelistDisabled', internalType: 'bool', type: 'bool' }],
    name: 'setValidatorWhitelistDisabled',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newWasmModuleRoot', internalType: 'bytes32', type: 'bytes32' }],
    name: 'setWasmModuleRoot',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'stakeToken',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'stakerCount',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalWithdrawableFunds',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'beacon', internalType: 'address', type: 'address' },
      { name: 'newImplementation', internalType: 'address', type: 'address' },
    ],
    name: 'upgradeBeacon',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newImplementation', internalType: 'address', type: 'address' }],
    name: 'upgradeSecondaryTo',
    outputs: [],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'newImplementation', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'upgradeSecondaryToAndCall',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newImplementation', internalType: 'address', type: 'address' }],
    name: 'upgradeTo',
    outputs: [],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'newImplementation', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'validatorUtils',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'validatorWalletCreator',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'validatorWhitelistDisabled',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'wasmModuleRoot',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'withdrawableFunds',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'zombieNum', internalType: 'uint256', type: 'uint256' }],
    name: 'zombieAddress',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'zombieCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'zombieNum', internalType: 'uint256', type: 'uint256' }],
    name: 'zombieLatestStakedNode',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'VALIDATOR_AFK_BLOCKS',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [{ name: 'stakerAddress', internalType: 'address', type: 'address' }],
    name: 'addToDeposit',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'challengeIndex', internalType: 'uint256', type: 'uint256' },
      { name: 'winningStaker', internalType: 'address', type: 'address' },
      { name: 'losingStaker', internalType: 'address', type: 'address' },
    ],
    name: 'completeChallenge',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'blockHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'sendRoot', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'confirmNextNode',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'nodeNum', internalType: 'uint64', type: 'uint64' }],
    name: 'countStakedZombies',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'nodeNum', internalType: 'uint64', type: 'uint64' }],
    name: 'countZombiesStakedOnChildren',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'stakers', internalType: 'address[2]', type: 'address[2]' },
      { name: 'nodeNums', internalType: 'uint64[2]', type: 'uint64[2]' },
      { name: 'machineStatuses', internalType: 'enum MachineStatus[2]', type: 'uint8[2]' },
      {
        name: 'globalStates',
        internalType: 'struct GlobalState[2]',
        type: 'tuple[2]',
        components: [
          { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
          { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
        ],
      },
      { name: 'numBlocks', internalType: 'uint64', type: 'uint64' },
      { name: 'secondExecutionHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'proposedBlocks', internalType: 'uint256[2]', type: 'uint256[2]' },
      { name: 'wasmModuleRoots', internalType: 'bytes32[2]', type: 'bytes32[2]' },
    ],
    name: 'createChallenge',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'currentRequiredStake',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_stakeToken', internalType: 'address', type: 'address' }],
    name: 'initialize',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'isERC20Enabled',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'nodeNum', internalType: 'uint64', type: 'uint64' },
      { name: 'nodeHash', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'newStakeOnExistingNode',
    outputs: [],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      {
        name: 'assertion',
        internalType: 'struct Assertion',
        type: 'tuple',
        components: [
          {
            name: 'beforeState',
            internalType: 'struct ExecutionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct ExecutionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
            ],
          },
          { name: 'numBlocks', internalType: 'uint64', type: 'uint64' },
        ],
      },
      { name: 'expectedNodeHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'prevNodeInboxMaxCount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'newStakeOnNewNode',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'target', internalType: 'uint256', type: 'uint256' }],
    name: 'reduceDeposit',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'stakerAddress', internalType: 'address', type: 'address' }],
    name: 'rejectNextNode',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'startIndex', internalType: 'uint256', type: 'uint256' }],
    name: 'removeOldZombies',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'removeWhitelistAfterFork',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'removeWhitelistAfterValidatorAfk',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'zombieNum', internalType: 'uint256', type: 'uint256' },
      { name: 'maxNodes', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'removeZombie',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'nodeNum', internalType: 'uint256', type: 'uint256' }],
    name: 'requireUnresolved',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'requireUnresolvedExists',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'blockNumber', internalType: 'uint256', type: 'uint256' },
      { name: 'firstUnresolvedNodeNum', internalType: 'uint64', type: 'uint64' },
      { name: 'latestCreatedNode', internalType: 'uint64', type: 'uint64' },
    ],
    name: 'requiredStake',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'stakerAddress', internalType: 'address', type: 'address' }],
    name: 'returnOldDeposit',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'nodeNum', internalType: 'uint64', type: 'uint64' },
      { name: 'nodeHash', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'stakeOnExistingNode',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: 'assertion',
        internalType: 'struct Assertion',
        type: 'tuple',
        components: [
          {
            name: 'beforeState',
            internalType: 'struct ExecutionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct ExecutionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
            ],
          },
          { name: 'numBlocks', internalType: 'uint64', type: 'uint64' },
        ],
      },
      { name: 'expectedNodeHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'prevNodeInboxMaxCount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'stakeOnNewNode',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'withdrawStakerFunds',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
] as const;
