//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Rollup
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const rollupABI = [
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'previousAdmin', internalType: 'address', type: 'address', indexed: false },
      { name: 'newAdmin', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'AdminChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'anyTrustFastConfirmer', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'AnyTrustFastConfirmerSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'assertionHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'blockHash', internalType: 'bytes32', type: 'bytes32', indexed: false },
      { name: 'sendRoot', internalType: 'bytes32', type: 'bytes32', indexed: false },
    ],
    name: 'AssertionConfirmed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'assertionHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'parentAssertionHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'assertion',
        internalType: 'struct AssertionInputs',
        type: 'tuple',
        components: [
          {
            name: 'beforeStateData',
            internalType: 'struct BeforeStateData',
            type: 'tuple',
            components: [
              { name: 'prevPrevAssertionHash', internalType: 'bytes32', type: 'bytes32' },
              { name: 'sequencerBatchAcc', internalType: 'bytes32', type: 'bytes32' },
              {
                name: 'configData',
                internalType: 'struct ConfigData',
                type: 'tuple',
                components: [
                  { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32' },
                  { name: 'requiredStake', internalType: 'uint256', type: 'uint256' },
                  { name: 'challengeManager', internalType: 'address', type: 'address' },
                  { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64' },
                  { name: 'nextInboxPosition', internalType: 'uint64', type: 'uint64' },
                ],
              },
            ],
          },
          {
            name: 'beforeState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
        ],
        indexed: false,
      },
      { name: 'afterInboxBatchAcc', internalType: 'bytes32', type: 'bytes32', indexed: false },
      { name: 'inboxMaxCount', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32', indexed: false },
      { name: 'requiredStake', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'challengeManager', internalType: 'address', type: 'address', indexed: false },
      { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64', indexed: false },
    ],
    name: 'AssertionCreated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'assertionHash', internalType: 'bytes32', type: 'bytes32', indexed: true }],
    name: 'AssertionForceConfirmed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'assertionHash', internalType: 'bytes32', type: 'bytes32', indexed: true }],
    name: 'AssertionForceCreated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'newBaseStake', internalType: 'uint256', type: 'uint256', indexed: false }],
    name: 'BaseStakeSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'beacon', internalType: 'address', type: 'address', indexed: true }],
    name: 'BeaconUpgraded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'challengeManager', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'ChallengeManagerSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'newConfirmPeriod', internalType: 'uint64', type: 'uint64', indexed: false }],
    name: 'ConfirmPeriodBlocksSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'inbox', internalType: 'address', type: 'address', indexed: false },
      { name: 'enabled', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'DelayedInboxSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'inbox', internalType: 'address', type: 'address', indexed: false }],
    name: 'InboxSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'version', internalType: 'uint8', type: 'uint8', indexed: false }],
    name: 'Initialized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'newLoserStakerEscrow', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'LoserStakeEscrowSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'newPeriod', internalType: 'uint256', type: 'uint256', indexed: false }],
    name: 'MinimumAssertionPeriodSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'outbox', internalType: 'address', type: 'address', indexed: false }],
    name: 'OldOutboxRemoved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'outbox', internalType: 'address', type: 'address', indexed: false }],
    name: 'OutboxSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'account', internalType: 'address', type: 'address', indexed: false }],
    name: 'Paused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'challengeIndex', internalType: 'uint64', type: 'uint64', indexed: true },
      { name: 'asserter', internalType: 'address', type: 'address', indexed: false },
      { name: 'challenger', internalType: 'address', type: 'address', indexed: false },
      { name: 'challengedAssertion', internalType: 'uint64', type: 'uint64', indexed: false },
    ],
    name: 'RollupChallengeStarted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'machineHash', internalType: 'bytes32', type: 'bytes32', indexed: false },
      { name: 'chainId', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'RollupInitialized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'newSequencerInbox', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'SequencerInboxSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'staker', internalType: 'address[]', type: 'address[]', indexed: false }],
    name: 'StakersForceRefunded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'account', internalType: 'address', type: 'address', indexed: false }],
    name: 'Unpaused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'implementation', internalType: 'address', type: 'address', indexed: true }],
    name: 'Upgraded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'implementation', internalType: 'address', type: 'address', indexed: true }],
    name: 'UpgradedSecondary',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'withdrawalAddress', internalType: 'address', type: 'address', indexed: true },
      { name: 'initialBalance', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'finalBalance', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'UserStakeUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'initialBalance', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'finalBalance', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'UserWithdrawableFundsUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'newPeriod', internalType: 'uint256', type: 'uint256', indexed: false }],
    name: 'ValidatorAfkBlocksSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: '_validatorWhitelistDisabled', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'ValidatorWhitelistDisabledSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'validators', internalType: 'address[]', type: 'address[]', indexed: false },
      { name: 'enabled', internalType: 'bool[]', type: 'bool[]', indexed: false },
    ],
    name: 'ValidatorsSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'newWasmModuleRoot', internalType: 'bytes32', type: 'bytes32', indexed: false },
    ],
    name: 'WasmModuleRootSet',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: '_stakerMap',
    outputs: [
      { name: 'amountStaked', internalType: 'uint256', type: 'uint256' },
      { name: 'latestStakedAssertion', internalType: 'bytes32', type: 'bytes32' },
      { name: 'index', internalType: 'uint64', type: 'uint64' },
      { name: 'isStaked', internalType: 'bool', type: 'bool' },
      { name: 'withdrawalAddress', internalType: 'address', type: 'address' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'amountStaked',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'anyTrustFastConfirmer',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'baseStake',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'bridge',
    outputs: [{ name: '', internalType: 'contract IBridge', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'chainId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'challengeGracePeriodBlocks',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'challengeManager',
    outputs: [{ name: '', internalType: 'contract IEdgeChallengeManager', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'confirmPeriodBlocks',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'newBaseStake', internalType: 'uint256', type: 'uint256' },
      { name: 'latestNextInboxPosition', internalType: 'uint64', type: 'uint64' },
    ],
    name: 'decreaseBaseStake',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'parentAssertionHash', internalType: 'bytes32', type: 'bytes32' },
      {
        name: 'confirmState',
        internalType: 'struct AssertionState',
        type: 'tuple',
        components: [
          {
            name: 'globalState',
            internalType: 'struct GlobalState',
            type: 'tuple',
            components: [
              { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
              { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
            ],
          },
          { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
          { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
        ],
      },
      { name: 'inboxAcc', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'forceConfirmAssertion',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'prevAssertionHash', internalType: 'bytes32', type: 'bytes32' },
      {
        name: 'assertion',
        internalType: 'struct AssertionInputs',
        type: 'tuple',
        components: [
          {
            name: 'beforeStateData',
            internalType: 'struct BeforeStateData',
            type: 'tuple',
            components: [
              { name: 'prevPrevAssertionHash', internalType: 'bytes32', type: 'bytes32' },
              { name: 'sequencerBatchAcc', internalType: 'bytes32', type: 'bytes32' },
              {
                name: 'configData',
                internalType: 'struct ConfigData',
                type: 'tuple',
                components: [
                  { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32' },
                  { name: 'requiredStake', internalType: 'uint256', type: 'uint256' },
                  { name: 'challengeManager', internalType: 'address', type: 'address' },
                  { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64' },
                  { name: 'nextInboxPosition', internalType: 'uint64', type: 'uint64' },
                ],
              },
            ],
          },
          {
            name: 'beforeState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
        ],
      },
      { name: 'expectedAssertionHash', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'forceCreateAssertion',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address[]', type: 'address[]' }],
    name: 'forceRefundStaker',
    outputs: [],
  },
  {
    stateMutability: 'pure',
    type: 'function',
    inputs: [],
    name: 'genesisAssertionHash',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getAssertion',
    outputs: [
      {
        name: '',
        internalType: 'struct AssertionNode',
        type: 'tuple',
        components: [
          { name: 'firstChildBlock', internalType: 'uint64', type: 'uint64' },
          { name: 'secondChildBlock', internalType: 'uint64', type: 'uint64' },
          { name: 'createdAtBlock', internalType: 'uint64', type: 'uint64' },
          { name: 'isFirstChild', internalType: 'bool', type: 'bool' },
          { name: 'status', internalType: 'enum AssertionStatus', type: 'uint8' },
          { name: 'configHash', internalType: 'bytes32', type: 'bytes32' },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getAssertionCreationBlockForLogLookup',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getFirstChildCreationBlock',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getSecondChildCreationBlock',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'getStaker',
    outputs: [
      {
        name: '',
        internalType: 'struct IRollupCore.Staker',
        type: 'tuple',
        components: [
          { name: 'amountStaked', internalType: 'uint256', type: 'uint256' },
          { name: 'latestStakedAssertion', internalType: 'bytes32', type: 'bytes32' },
          { name: 'index', internalType: 'uint64', type: 'uint64' },
          { name: 'isStaked', internalType: 'bool', type: 'bool' },
          { name: 'withdrawalAddress', internalType: 'address', type: 'address' },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'stakerNum', internalType: 'uint64', type: 'uint64' }],
    name: 'getStakerAddress',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getValidators',
    outputs: [{ name: '', internalType: 'address[]', type: 'address[]' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'inbox',
    outputs: [{ name: '', internalType: 'contract IInboxBase', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newBaseStake', internalType: 'uint256', type: 'uint256' }],
    name: 'increaseBaseStake',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: 'config',
        internalType: 'struct Config',
        type: 'tuple',
        components: [
          { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64' },
          { name: 'stakeToken', internalType: 'address', type: 'address' },
          { name: 'baseStake', internalType: 'uint256', type: 'uint256' },
          { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32' },
          { name: 'owner', internalType: 'address', type: 'address' },
          { name: 'loserStakeEscrow', internalType: 'address', type: 'address' },
          { name: 'chainId', internalType: 'uint256', type: 'uint256' },
          { name: 'chainConfig', internalType: 'string', type: 'string' },
          { name: 'minimumAssertionPeriod', internalType: 'uint256', type: 'uint256' },
          { name: 'validatorAfkBlocks', internalType: 'uint64', type: 'uint64' },
          { name: 'miniStakeValues', internalType: 'uint256[]', type: 'uint256[]' },
          {
            name: 'sequencerInboxMaxTimeVariation',
            internalType: 'struct ISequencerInbox.MaxTimeVariation',
            type: 'tuple',
            components: [
              { name: 'delayBlocks', internalType: 'uint256', type: 'uint256' },
              { name: 'futureBlocks', internalType: 'uint256', type: 'uint256' },
              { name: 'delaySeconds', internalType: 'uint256', type: 'uint256' },
              { name: 'futureSeconds', internalType: 'uint256', type: 'uint256' },
            ],
          },
          { name: 'layerZeroBlockEdgeHeight', internalType: 'uint256', type: 'uint256' },
          { name: 'layerZeroBigStepEdgeHeight', internalType: 'uint256', type: 'uint256' },
          { name: 'layerZeroSmallStepEdgeHeight', internalType: 'uint256', type: 'uint256' },
          {
            name: 'genesisAssertionState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
          { name: 'genesisInboxCount', internalType: 'uint256', type: 'uint256' },
          { name: 'anyTrustFastConfirmer', internalType: 'address', type: 'address' },
          { name: 'numBigStepLevel', internalType: 'uint8', type: 'uint8' },
          { name: 'challengeGracePeriodBlocks', internalType: 'uint64', type: 'uint64' },
          {
            name: 'bufferConfig',
            internalType: 'struct BufferConfig',
            type: 'tuple',
            components: [
              { name: 'threshold', internalType: 'uint64', type: 'uint64' },
              { name: 'max', internalType: 'uint64', type: 'uint64' },
              { name: 'replenishRateInBasis', internalType: 'uint64', type: 'uint64' },
            ],
          },
          { name: 'dataCostEstimate', internalType: 'uint256', type: 'uint256' },
        ],
      },
      {
        name: 'connectedContracts',
        internalType: 'struct ContractDependencies',
        type: 'tuple',
        components: [
          { name: 'bridge', internalType: 'contract IBridge', type: 'address' },
          { name: 'sequencerInbox', internalType: 'contract ISequencerInbox', type: 'address' },
          { name: 'inbox', internalType: 'contract IInboxBase', type: 'address' },
          { name: 'outbox', internalType: 'contract IOutbox', type: 'address' },
          { name: 'rollupEventInbox', internalType: 'contract IRollupEventInbox', type: 'address' },
          {
            name: 'challengeManager',
            internalType: 'contract IEdgeChallengeManager',
            type: 'address',
          },
          { name: 'rollupAdminLogic', internalType: 'address', type: 'address' },
          { name: 'rollupUserLogic', internalType: 'contract IRollupUser', type: 'address' },
          { name: 'validatorWalletCreator', internalType: 'address', type: 'address' },
        ],
      },
    ],
    name: 'initialize',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'isFirstChild',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'isPending',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'isStaked',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'validator', internalType: 'address', type: 'address' }],
    name: 'isValidator',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'latestConfirmed',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'latestStakedAssertion',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'loserStakeEscrow',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'minimumAssertionPeriod',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'outbox',
    outputs: [{ name: '', internalType: 'contract IOutbox', type: 'address' }],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'pause', outputs: [] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'paused',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_outbox', internalType: 'address', type: 'address' }],
    name: 'removeOldOutbox',
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'resume', outputs: [] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'rollupDeploymentBlock',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'rollupEventInbox',
    outputs: [{ name: '', internalType: 'contract IRollupEventInbox', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'sequencerInbox',
    outputs: [{ name: '', internalType: 'contract ISequencerInbox', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_anyTrustFastConfirmer', internalType: 'address', type: 'address' }],
    name: 'setAnyTrustFastConfirmer',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_challengeManager', internalType: 'address', type: 'address' }],
    name: 'setChallengeManager',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newConfirmPeriod', internalType: 'uint64', type: 'uint64' }],
    name: 'setConfirmPeriodBlocks',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_inbox', internalType: 'address', type: 'address' },
      { name: '_enabled', internalType: 'bool', type: 'bool' },
    ],
    name: 'setDelayedInbox',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newInbox', internalType: 'contract IInboxBase', type: 'address' }],
    name: 'setInbox',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newLoserStakerEscrow', internalType: 'address', type: 'address' }],
    name: 'setLoserStakeEscrow',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newPeriod', internalType: 'uint256', type: 'uint256' }],
    name: 'setMinimumAssertionPeriod',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_outbox', internalType: 'contract IOutbox', type: 'address' }],
    name: 'setOutbox',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'setOwner',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_sequencerInbox', internalType: 'address', type: 'address' }],
    name: 'setSequencerInbox',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_validator', internalType: 'address[]', type: 'address[]' },
      { name: '_val', internalType: 'bool[]', type: 'bool[]' },
    ],
    name: 'setValidator',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newAfkBlocks', internalType: 'uint64', type: 'uint64' }],
    name: 'setValidatorAfkBlocks',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_validatorWhitelistDisabled', internalType: 'bool', type: 'bool' }],
    name: 'setValidatorWhitelistDisabled',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newWasmModuleRoot', internalType: 'bytes32', type: 'bytes32' }],
    name: 'setWasmModuleRoot',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'stakeToken',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'stakerCount',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalWithdrawableFunds',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newImplementation', internalType: 'address', type: 'address' }],
    name: 'upgradeSecondaryTo',
    outputs: [],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'newImplementation', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'upgradeSecondaryToAndCall',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newImplementation', internalType: 'address', type: 'address' }],
    name: 'upgradeTo',
    outputs: [],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'newImplementation', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
  },
  {
    stateMutability: 'pure',
    type: 'function',
    inputs: [
      { name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' },
      {
        name: 'state',
        internalType: 'struct AssertionState',
        type: 'tuple',
        components: [
          {
            name: 'globalState',
            internalType: 'struct GlobalState',
            type: 'tuple',
            components: [
              { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
              { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
            ],
          },
          { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
          { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
        ],
      },
      { name: 'prevAssertionHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'inboxAcc', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'validateAssertionHash',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' },
      {
        name: 'configData',
        internalType: 'struct ConfigData',
        type: 'tuple',
        components: [
          { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32' },
          { name: 'requiredStake', internalType: 'uint256', type: 'uint256' },
          { name: 'challengeManager', internalType: 'address', type: 'address' },
          { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64' },
          { name: 'nextInboxPosition', internalType: 'uint64', type: 'uint64' },
        ],
      },
    ],
    name: 'validateConfig',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'validatorAfkBlocks',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'validatorWalletCreator',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'validatorWhitelistDisabled',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'wasmModuleRoot',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'withdrawableFunds',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'staker', internalType: 'address', type: 'address' }],
    name: 'withdrawalAddress',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'stakerAddress', internalType: 'address', type: 'address' },
      { name: 'expectedWithdrawalAddress', internalType: 'address', type: 'address' },
      { name: 'tokenAmount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'addToDeposit',
    outputs: [],
  },
  {
    stateMutability: 'pure',
    type: 'function',
    inputs: [
      { name: 'prevAssertionHash', internalType: 'bytes32', type: 'bytes32' },
      {
        name: 'state',
        internalType: 'struct AssertionState',
        type: 'tuple',
        components: [
          {
            name: 'globalState',
            internalType: 'struct GlobalState',
            type: 'tuple',
            components: [
              { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
              { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
            ],
          },
          { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
          { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
        ],
      },
      { name: 'inboxAcc', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'computeAssertionHash',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'prevAssertionHash', internalType: 'bytes32', type: 'bytes32' },
      {
        name: 'confirmState',
        internalType: 'struct AssertionState',
        type: 'tuple',
        components: [
          {
            name: 'globalState',
            internalType: 'struct GlobalState',
            type: 'tuple',
            components: [
              { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
              { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
            ],
          },
          { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
          { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
        ],
      },
      { name: 'winningEdgeId', internalType: 'bytes32', type: 'bytes32' },
      {
        name: 'prevConfig',
        internalType: 'struct ConfigData',
        type: 'tuple',
        components: [
          { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32' },
          { name: 'requiredStake', internalType: 'uint256', type: 'uint256' },
          { name: 'challengeManager', internalType: 'address', type: 'address' },
          { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64' },
          { name: 'nextInboxPosition', internalType: 'uint64', type: 'uint64' },
        ],
      },
      { name: 'inboxAcc', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'confirmAssertion',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'assertionHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'parentAssertionHash', internalType: 'bytes32', type: 'bytes32' },
      {
        name: 'confirmState',
        internalType: 'struct AssertionState',
        type: 'tuple',
        components: [
          {
            name: 'globalState',
            internalType: 'struct GlobalState',
            type: 'tuple',
            components: [
              { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
              { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
            ],
          },
          { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
          { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
        ],
      },
      { name: 'inboxAcc', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'fastConfirmAssertion',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: 'assertion',
        internalType: 'struct AssertionInputs',
        type: 'tuple',
        components: [
          {
            name: 'beforeStateData',
            internalType: 'struct BeforeStateData',
            type: 'tuple',
            components: [
              { name: 'prevPrevAssertionHash', internalType: 'bytes32', type: 'bytes32' },
              { name: 'sequencerBatchAcc', internalType: 'bytes32', type: 'bytes32' },
              {
                name: 'configData',
                internalType: 'struct ConfigData',
                type: 'tuple',
                components: [
                  { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32' },
                  { name: 'requiredStake', internalType: 'uint256', type: 'uint256' },
                  { name: 'challengeManager', internalType: 'address', type: 'address' },
                  { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64' },
                  { name: 'nextInboxPosition', internalType: 'uint64', type: 'uint64' },
                ],
              },
            ],
          },
          {
            name: 'beforeState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
        ],
      },
      { name: 'expectedAssertionHash', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'fastConfirmNewAssertion',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_stakeToken', internalType: 'address', type: 'address' }],
    name: 'initialize',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'tokenAmount', internalType: 'uint256', type: 'uint256' },
      { name: '_withdrawalAddress', internalType: 'address', type: 'address' },
    ],
    name: 'newStake',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'tokenAmount', internalType: 'uint256', type: 'uint256' },
      {
        name: 'assertion',
        internalType: 'struct AssertionInputs',
        type: 'tuple',
        components: [
          {
            name: 'beforeStateData',
            internalType: 'struct BeforeStateData',
            type: 'tuple',
            components: [
              { name: 'prevPrevAssertionHash', internalType: 'bytes32', type: 'bytes32' },
              { name: 'sequencerBatchAcc', internalType: 'bytes32', type: 'bytes32' },
              {
                name: 'configData',
                internalType: 'struct ConfigData',
                type: 'tuple',
                components: [
                  { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32' },
                  { name: 'requiredStake', internalType: 'uint256', type: 'uint256' },
                  { name: 'challengeManager', internalType: 'address', type: 'address' },
                  { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64' },
                  { name: 'nextInboxPosition', internalType: 'uint64', type: 'uint64' },
                ],
              },
            ],
          },
          {
            name: 'beforeState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
        ],
      },
      { name: 'expectedAssertionHash', internalType: 'bytes32', type: 'bytes32' },
      { name: '_withdrawalAddress', internalType: 'address', type: 'address' },
    ],
    name: 'newStakeOnNewAssertion',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'tokenAmount', internalType: 'uint256', type: 'uint256' },
      {
        name: 'assertion',
        internalType: 'struct AssertionInputs',
        type: 'tuple',
        components: [
          {
            name: 'beforeStateData',
            internalType: 'struct BeforeStateData',
            type: 'tuple',
            components: [
              { name: 'prevPrevAssertionHash', internalType: 'bytes32', type: 'bytes32' },
              { name: 'sequencerBatchAcc', internalType: 'bytes32', type: 'bytes32' },
              {
                name: 'configData',
                internalType: 'struct ConfigData',
                type: 'tuple',
                components: [
                  { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32' },
                  { name: 'requiredStake', internalType: 'uint256', type: 'uint256' },
                  { name: 'challengeManager', internalType: 'address', type: 'address' },
                  { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64' },
                  { name: 'nextInboxPosition', internalType: 'uint64', type: 'uint64' },
                ],
              },
            ],
          },
          {
            name: 'beforeState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
        ],
      },
      { name: 'expectedAssertionHash', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'newStakeOnNewAssertion',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'target', internalType: 'uint256', type: 'uint256' }],
    name: 'reduceDeposit',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'removeWhitelistAfterFork',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'removeWhitelistAfterValidatorAfk',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'returnOldDeposit',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'stakerAddress', internalType: 'address', type: 'address' }],
    name: 'returnOldDepositFor',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: 'assertion',
        internalType: 'struct AssertionInputs',
        type: 'tuple',
        components: [
          {
            name: 'beforeStateData',
            internalType: 'struct BeforeStateData',
            type: 'tuple',
            components: [
              { name: 'prevPrevAssertionHash', internalType: 'bytes32', type: 'bytes32' },
              { name: 'sequencerBatchAcc', internalType: 'bytes32', type: 'bytes32' },
              {
                name: 'configData',
                internalType: 'struct ConfigData',
                type: 'tuple',
                components: [
                  { name: 'wasmModuleRoot', internalType: 'bytes32', type: 'bytes32' },
                  { name: 'requiredStake', internalType: 'uint256', type: 'uint256' },
                  { name: 'challengeManager', internalType: 'address', type: 'address' },
                  { name: 'confirmPeriodBlocks', internalType: 'uint64', type: 'uint64' },
                  { name: 'nextInboxPosition', internalType: 'uint64', type: 'uint64' },
                ],
              },
            ],
          },
          {
            name: 'beforeState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
          {
            name: 'afterState',
            internalType: 'struct AssertionState',
            type: 'tuple',
            components: [
              {
                name: 'globalState',
                internalType: 'struct GlobalState',
                type: 'tuple',
                components: [
                  { name: 'bytes32Vals', internalType: 'bytes32[2]', type: 'bytes32[2]' },
                  { name: 'u64Vals', internalType: 'uint64[2]', type: 'uint64[2]' },
                ],
              },
              { name: 'machineStatus', internalType: 'enum MachineStatus', type: 'uint8' },
              { name: 'endHistoryRoot', internalType: 'bytes32', type: 'bytes32' },
            ],
          },
        ],
      },
      { name: 'expectedAssertionHash', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'stakeOnNewAssertion',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'withdrawStakerFunds',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
] as const;
